### ISSUE TITLE
Uncaught exception due to Mongo error

### ISSUE THREAD

**Issue by purasu1** [thundercookie15/PomuBot#3]
I've been running a copy of PomuBot for a while now, and I just started getting constant errors in my logging channel, several times a minute:

![Screenshot_20231021_091206](https://github.com/thundercookie15/PomuBot/assets/113078044/4c4872c4-c25a-4648-828b-4716c1869cc5)

Looking at the logs, I'm seeing a stack trace that looks like this:

```js
Uncaught exception: MongoServerError: Plan executor error during findAndModify :: caused by :: Resulting document after update is larger than 16777216
    at Connection.onMessage (/usr/home/pomubot/PomuBot/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:202:26)
    at MessageStream.<anonymous> (/usr/home/pomubot/PomuBot/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/usr/home/pomubot/PomuBot/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
    at MessageStream._write (/usr/home/pomubot/PomuBot/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

(apologies for any typos, for various reasons I had to copy this by hand)

**Comment by thundercookie15** [comment]
Taking a quick look, this appears to be an issue with MongoDB itself. 
I am very busy with work coming week and won’t be home for the weekend.
However I’ll try and get this issue fixed as soon as I have the time for it.

for now a quick solution should be a restart of the bot since that will clear out any old data.

**Comment by purasu1** [comment]
I did reset a couple of times, both the bot and mongo, as well as restarting the container, and the error messages continue to be printed several times per minute.

**Comment by purasu1** [comment]
Not sure if this is related, but it looks like TL blacklisting is also broken currently.

![image](https://github.com/thundercookie15/PomuBot/assets/113078044/05a8ccf2-0f8f-432e-91f1-e4b5b854aa7f)
